### ISSUE TITLE
validate_hierarchy call in R Pipeline/Modules/050 is not working

### ISSUE THREAD

**Issue by arilamstein** [BAAQMD/tbltools#11]
Here is the error:
```
# read in master list
path = BY2015_path("Categories/BY2015_categories_assignment.xlsx")
# excel_sheets(path)
master_list = read_excel(path, "BY2015_categories (master list)")
validate_hierarchy(master_list)

Error in if (min(h_indices) > 1) { : 
  missing value where TRUE/FALSE needed
```

**Comment by dholstius** [comment]
Closed the problem with `tbltools::validate_hierarchy()` via [2653ad7](https://github.com/BAAQMD/tbltools/commit/2653ad7932ff287c2de62a47c02a63ec992dad3f) in the `tbltools` repo.

It's not possible to [transfer issues](https://docs.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository) between a private repository (like this one) and a public repository, unfortunately. This complicates our issue-filing scheme. Consequently it will slow down other BY2015 work I'm doing. I see two potential fixes for that:

1. Allocate staff (like @ydu0316 or @arihusain) who can help organize issues. 
2. Make the `BY2015-methodology` repo public, rather than private (as it is now).

Keeping this open because a decision (1, 2, something else, or `wontfix`) needs to be made by @abhinavguha and/or @songbai-BAAQMD

**Comment by songbai-BAAQMD** [comment]
@dholstius, are there any concerns if we make `BY2015-methodology` repo public?  I assume that it would be visible to everyone if we change it to public; but the BY2011 repo is a public one already, is that right?

**Comment by dholstius** [comment]
@songbai-BAAQMD, I have no concerns. EI staff were the ones who wanted to make it private. Maybe you or @abhinavguha should poll them to find out why?

**Comment by arilamstein** [comment]
@dholstius I restarted my R session and then ran the same code in the same file again. It generates the same error. 

I am new to the shared server environment. Is there something I should manually be doing to get your change, or was it supposed to "just work" for me?

**Comment by abhinavguha** [comment]
@dholstius  we will get a consensus on this during our weekly meeting today and have a decision ready, hopefully, by end of day.

**Comment by dholstius** [comment]
@arilamstein , do you get this same problem on the new RStudio server?

**Comment by arilamstein** [comment]
> @arilamstein , do you get this same problem on the new RStudio server?

No. It appear fixed. I am closing.
