### ISSUE TITLE
Invalid call to DataBank?

### ISSUE THREAD

**Issue by arilamstein** [BAAQMD/tbltools#14]
Line 76 of `with_hierarchy.R` has this code:
```
    # Handle the case where a t-table is provided directly
    # (it has to be reshaped!)
    hierarchy_object <-
      DataBank::DB_hierarchy(
        using = using,
        verbose = verbose)
```

I encountered it because the package does not Import or Depend on DataBank in the DESCRIPTION file, which is causing errors during R CMD CHECK.

The issue actually turns out to be more significant than a naming issue. It appears that DataBank does not have a function called `DB_hierarchy` at all!
```
> library(DataBank)
Loading required package: welcome
Today is Thu Apr  8 11:50:47 2021
Loading required package: ensurer
Loading required package: memoise
Loading required package: Ingres
Loading required package: cacher
Error: package ‘tbltools’ required by ‘Ingres’ could not be found
> DataBank::DB_hierarchy
Error: 'DB_hierarchy' is not an exported object from 'namespace:DataBank'
> DataBank:::DB_hierarchy
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'DB_hierarchy' not found
```

@dholstius can you please comment? I notice that DataBank exports two functions with similar names: `DB_category_hierarchy` and `DB_SIC_hierarchy`. Is it possible that `DB_hierarchy` used to exist but was deleted in favor of these other functions? What should this line be?

**Comment by dholstius** [comment]
Taking the issue on its face value, `DB_hierarchy()` should just be replaced by `DB_category_hierarchy()`.

There's a bit of a circular dependency here, in that the `DataBank` package really does depend heavily on `tbltools`. I'm OK with it, though not comfortably so, because the invocation of `DB_category_hierarchy()` only happens in a particular case, where `using` is identical (basically) to `Ingres::t0327`. And that's just there for long-ago-compatibility reasons. 

Proposal:

1. Replace `DB_hierarchy()` with `DB_category_hierarchy()`;
2. Deprecate this edge case / backwards-compatibility; 
3. Note any warnings that arise in downstream contexts, and fix those; then 
4. Eventually make it `.Defunct()`.

I'll take care of (1) and (2) in a PR.

\* The same circularity applies to `Ingres`, which also depends on `tbltools`.

**Comment by arilamstein** [comment]
@dholstius Thanks so much for your quick attention to this (and all the other issues).

Hopefully at some point I get a better knowledge of what all these packages do, and can help you sort out any circular dependencies.
